apiVersion: apps/v1
kind: Deployment

metadata:
  name: hpa-demo-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: hpa-demo-app

  template:
    metadata:
      labels:
        app: hpa-demo-app

    spec:
      containers:
      - name: nginx-container
        image: nginx

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "256Mi"